{% set name = "fqe" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fqe-{{ version }}.tar.gz
  sha256: 7aadb5292253ad82dd282a7e9d773134787e05e267ea8c995f5d9ce060074518

build:
  number: 1
  skip: true  # [win or py==37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - cython
    - numpy
    - pip
    - python
    - scipy
    - setuptools
    - wheel
  run:
    - cirq-core >=0.15.0
    - cirq-google >=0.15.0
    - cython
    - jupyter
    - {{ pin_compatible('numpy') }}
    - openfermion >=1.5.0
    - pyasn1-modules ==0.2.7
    - python
    - scipy
    - sphinx >=2.3.1

test:
  imports:
    - fqe
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.openfermion.org
  summary: OpenFermion Fermionic Quantum Emulator
  description: |
    The Fermionic Quantum Emulator (FQE) is a light weight fermionic circuit simulator.
    The emulator uses number and projected spin quantum numbers to reduce the
    cost of simulating state evolutions under fermionic generators.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/quantumlib/OpenFermion-FQE

extra:
  recipe-maintainers:
    - BastianZim
